sudo: false
branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      
env:
  global:
    - GH_REPO_NAME: SudokuSolver
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxygen.in
    - GH_REPO_REF: github.com/maede97/SudokuSolver.git

script:
  - gcc -v;
  - mkdir build;
  - cd build;
  - cmake ..;
  - make

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
