sudo: false
branches:
  only:
    - master

os: linux
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - export CC=gcc-8;
  - export CXX=g++-8;
  - ./install.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
